In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/sample.csv")

df

     id  mean  median  mode   max   min
0   101  10.0     NaN   NaN   NaN   NaN
1   101   NaN     NaN   9.0   NaN   NaN
2   101   NaN    11.5   NaN   NaN   NaN
3   101   NaN     NaN   NaN  20.0   NaN
4   101   NaN     NaN   NaN   NaN   0.0
5   102   NaN     NaN   NaN   NaN   1.0
6   102   NaN     NaN   NaN   NaN   NaN
7   102   NaN     NaN   NaN  50.0   NaN
8   102   NaN    14.5   NaN   NaN   NaN
9   102   9.5     NaN   NaN   NaN   NaN
10  103   NaN     NaN  25.0   NaN   NaN
11  103   NaN    13.0   NaN   NaN   NaN
12  103  10.0     NaN   NaN   NaN   NaN
13  103   NaN     NaN   NaN  90.0   NaN
14  103   NaN     NaN   NaN   NaN  60.0
15  104   NaN     NaN  50.0   NaN   NaN
16  104   NaN     NaN   NaN  25.0   NaN
17  104   NaN     NaN   NaN   NaN  15.0
18  104   NaN    10.0   NaN   NaN   NaN
19  104   5.0     NaN   NaN   NaN   NaN
20  105   NaN     NaN   NaN   6.0   NaN
21  105   NaN     NaN   NaN   NaN   5.0
22  105   NaN     NaN  10.0   NaN   NaN
23  105   NaN     NaN   NaN   NaN   NaN
24  105   3.0     NaN   NaN   NaN   NaN

In [3]:
result_df = df.groupby('id').agg({
    'mean': 'mean',
    'median': 'median',
    'mode': lambda x: x.mode().iloc[0] if not x.mode().empty else None,
    'max': 'max',
    'min': 'min'
}).reset_index()

result_df

    id  mean  median  mode   max   min
0  101  10.0    11.5   9.0  20.0   0.0
1  102   9.5    14.5   NaN  50.0   1.0
2  103  10.0    13.0  25.0  90.0  60.0
3  104   5.0    10.0  50.0  25.0  15.0
4  105   3.0     NaN  10.0   6.0   5.0